# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10PxcgO5FADLWop7whV-nQNxydZm18kGi
"""


import streamlit as st
import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import load_model
import talib  # for RSI if you wish

st.title("Stock Trend & LSTM Prediction App")

ticker = st.text_input("Stock Symbol:", "AAPL")
start_date = st.date_input("Start Date", pd.to_datetime("2015-01-01"))
end_date = st.date_input("End Date", pd.to_datetime("today"))

if st.button("Run"):
    df = yf.download(ticker, start=start_date, end=end_date)
    st.write("Data Head:", df.head())
    
    df['MA50'] = df['Close'].rolling(50).mean()
    df['RSI'] = talib.RSI(df['Close'], timeperiod=14)
    
    fig, ax = plt.subplots()
    ax.plot(df['Close'], label="Close")
    ax.plot(df['MA50'], label="MA 50")
    ax.legend()
    st.pyplot(fig)
    
    model = load_model("lstm_model.h5")
    scaler = MinMaxScaler()
    # Prepare data for LSTM (similar to training pipeline)
    # Predict and plot actual vs. predicted...

